language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t prasanth/docker-react -f Dockerfile.dev .
script:
  - docker run prasanth/docker-react:latest npm run test -- --coverage

